apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: realtime-project
  region: eu-north-1
  version: '1.28'
iam:
  withOIDC: true

availabilityZones: 
  - eu-north-1a
  - eu-north-1b
  - eu-north-1c

managedNodeGroups:
  - name: realtime-project-ng
    instanceType: t2.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 30
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
